version: "3.8"

services:
  db:
    image: postgres:latest
    restart: always
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=budgetbuddy
      - POSTGRES_USER=budgetbuddy
      - PGDATA=/database
    volumes:
      - ./postgres:/docker-entrypoint-initdb.d
      - ./postgres/postgres.conf:/usr/local/share/postgresql/postgresql.conf
      - ./pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    ports:
      - 6379:6379
    # volumes:
    #   - ./redis_data:/data

  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    ports:
      - "5173:5173" # Map port 5173 on host to port 5173 in container
    volumes:
      - ./client/src:/app/client/src # Mount the client directory to the container

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8000:8000" # Map port 8000 on host to port 8000 in container
    volumes:
      - ./server:/app/server # Mount the server directory to the container
    env_file:
      - .env
    depends_on:
      - db
      - redis
# volumes:
#   - redis_data:
