version: "3.8"

services:
  server:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8000:8000" # Map port 8000 on host to port 8000 in container
    env_file:
      - prod.env
