name: CI/CD Pipeline

# Trigger deployment on push to main branch
on:
  push:
    branches:
      - main

jobs:
  #   First job, build the docker image and push it to Dockerhub
  build-and-push:
    name: build and push docker image to dockerhub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

        # Login to Dockerhub to allow github actions to be able to push to the repository.
      - name: Login to Dockerhub
        uses: docker/login-action@v3
        with:
          username: ${{secrets.DOCKERHUB_USERNAME}}
          password: ${{secrets.DOCKERHUB_TOKEN}}

      # Build the server production docker file, then push it to my dockerhub repo.
      - name: Build and push images
        uses: docker/build-push-action@v5
        with:
          context: ./server
          file: ./server/Dockerfile.prod
          push: true
          tags: abiliu018/prod-budgetbuddy-api:v5.0

  #   Now we need to SSH into the EC2 instance and restart the containers.
  deploy-to-ec2:
    runs-on: ubuntu-latest
    needs: build-and-push
    steps:
      - name: Deploy to EC2 instance
        uses: appleboy/ssh-action@master
        with:
          host: ${{secrets.EC2_HOST_DNS}}
          username: ${{secrets.USERNAME}}
          key: ${{secrets.EC2_SSH_KEY}}
          script: |
            cd ${{secrets.TARGET_DIR}}
            docker-compose -f docker-compose.prod.yml down || true
            docker rmi $(docker images -q) || true
            docker-compose -f docker-compose.prod up
